$("#people").append(`<option value="Charlie">Charlie</option>`);

quotes.Charlie = {
    wisdoms: [
        "The average adult farts enough in a day to fill a small child",
        "Batman's problem? He's too black",
        "A millionaire has one M&M",
        "Your eyes can only see",
        "Your fingers can obviously only feel, they can't communicate",
        "The problem with dolphins is that they take too long to get to the point",
        "Humans have electrical brain",
        "A bag is so much smaller than a fridge",
        "Just because your missing a hand, doesn't mean you can't kick",
    ],
    band_names: [
        "Fifth elephant?",
        "Sydney Moomins?"
    ],
    other: [
        "You're all my shlavantage",
        "Is a group of Jews, a Rabi?",
        "But I is not your plate",
        "Fuck you, I'm Sony",
        "I am Charlie!?",
        "You're putting too much leg into the shoe",
        "I'm following my compass gun",
        "I want to be the terrorist",
        "The more you punch, the more he shits",
        "You have to kill the moss bob!",
        "NASA? They do something with piss",
        "Take your own skin off",
        "What's that Jewish thing... salad cream?",
        "You don't want snotty testicles",
        "What's a Creamfield?",
        "She's just space Madeline",
        "What's abugania?",
        "I NEED TO WASH MY GOBLETS",
        "You broke my cocobowl",
        "I thought you meant the sexual gremlin",
        "He's full Hawkins!",
        "Your alarm lap went off",
        "They're just wearing their front clothes",
        "Don't dick the door",
        "I found 90% of a cat",
        "Have you ever seen a porn?",
        "In a law of court",
        "Lighbulbs for dinner",
        "What's gay furry porn?",
        "How do you say anger, angrily?",
        "I know what words are, at 2.5 times the speed",
        "I've been resurrected because I haven't died yet",
        "Nazi crafts",
        "Someone's an onion racist",
        "Can I show you my monster chain?",
        "I like sniffing taint",
        "Don't AWWWHHH me!",
        "I hooted in the wrong area",
        "I have the gift",
        "Hold and pinch the flap",
        "It's cow soap",
        "It's a big obscure pebble",
        "No sexual rugs!",
        "A moral support turkey twizzler",
        "It's a monster pocket"
    ]
};
