quotes.Will = {
    wisdoms: [
        "Boomerangs come back on their own terms",
        "Pizza Hut's not real",
        "We live in a meatless simulation",
        "Everything always goes back to the cheese factory",
        "Payday is just capitalist lube"
    ],
    band_names: [
        "Cruella Dickville",
        "The greasy poon"
    ],
    other: [
        "It's the whq'k sounds that are the trouble",
        "I just Big Toe'd the cone",
        "Does this make you cry Urban Tears?",
        "I'll just Microsoft Sam it",
        "I... LIKE... CUPS.",
        "I'm looking forward to the twin towers",
        "Let's watch people irradiate",
        "Jihad the titty",
        "I need to whack out my-knob-oly",
        "Can I be a mouse?",
        "No way, no therapy",
        "But I want to be a planet",
        "My toe is the same size as some healthy penises",
        "You know what's weird...? Carbonation down your penis",
        "Was that my goblin thoughts?",
        "You have to be good at waiting, really fast",
        "Stop screaming, we've already saved the NHS",
        "Did she have an elbow?",
        "Can I have one of those pyramids?",
        "My feet were little Voldemorts",
        "Hakuna my immune system",
        "I want to speak to my water",
        "It's a really beefy camel toe",
        "Milk can go fuck itself",
        "Secondary hindu's",
        "It was invented by Adult Hitler",
        "It only evolves if you shit on it",
        "You're neuro-diverse",
        "There's too much eew in the woo",
        "Goku? Boyku?",
        "Support the Sol Rings",
        "It's just Wuhan",
        "Absolutely bointless",
        "This looks like a Mew Two costume",
        "The Russian politican, Snaphisnekov",
        "You kiss so nice on the nose",
        "Municipal water",
        "Unicorns are feet sized",
        "Do popes lay eggs?",
        "Crotch falafel",
        "Charlie's my fish tank",
        "Let's not push our successes on people, Matthew",
        "It's a single-action banana",
        "The mange has come",
        "The spot is a decoy",
        "Everyone's a wanker",
        "Once it's on your face-face",
        "The second brain",
        "I'm a lighthouse",
        "Korma knees",
        "I can't unsee mustache",
        "Manwell's got karma",
        "I don't have a blachulars",
        "You gotta keep your tongue above the top teeth",
        "I want to have water and enjoy myself",
        "Let me just part the Serengeti",
        "Post-neck human",
        "Yo, gym-jew!",
        "Reactor 4 was just full of apples",
        "I can revolt from the window",
        "Plant bastard",
        "The navy gravy",
        "Take her down the dirt track",
        "Pinky promise with my meaty hand",
        "He's dyslogic",
        "I'll lick the table but nothing dirty",
        "I've just cumshot my face with an apple stick",
        "I'm a man of reach-arounds",
        "Did we just toe-dock?",
        "That's some reverse Ghibli shit",
        "Rhigubu!",
        "Comrade Cumrag",
        "No contest; is dwarf",
        "What will it take to stop you putting billboards in space?",
        "I had a poo at work",
        "I don't want to melt from the foot down",
        "Look at my soggy wotsit",
        "My white middle-class woman pyramid",
        "He is the babashallom",
        "Where's my curry person?",
        "I need some manual toasting",
        "The more I laugh, the dumber I get",
        "I'm momma's little moo cow",
        "Our shit-term memory",
    ]
};